AddonChecker/Models/CheckResultViewModel.cs
using AddonChecker.Checks;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AddonChecker.Models
{
    public class CheckResultViewModel
    {
        public string AddonName { get; set; }
        public int ChecksNumber { get; set; }
        public int FilesNumber { get; set; }
        public List<CheckResult> ChecksResult { get; set; }
    }
}

AddonChecker/Models/ErrorViewModel.cs
using System;

namespace AddonChecker.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AddonChecker/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AddonChecker.Models;
using System.IO;
using System.Threading;
using Microsoft.AspNetCore.Http;
using System.IO.Compression;
using AddonChecker.Checks.items;
using AddonChecker.Checks;
using System.Reflection;
using MySql.Data.MySqlClient;
using Microsoft.Extensions.Configuration;

namespace AddonChecker.Controllers
{
    public class BaseController : Controller
    {
        private IConfiguration configuration;

        public BaseController(IConfiguration iConfig)
        {
            configuration = iConfig;
        }

        [NonAction]
        private async void LogResult(CheckResultViewModel result)
        {
            try
            {
                MySqlConnection connection = new MySqlConnection
                {
                    ConnectionString = string.Format("server={0};user id={1};password={2};persistsecurityinfo=True;port={3};database={4};CharSet=utf8",
                       configuration.GetSection("DB").GetSection("IP").Value,
                       configuration.GetSection("DB").GetSection("User").Value,
                       configuration.GetSection("DB").GetSection("Password").Value,
                       configuration.GetSection("DB").GetSection("Port").Value,
                       configuration.GetSection("DB").GetSection("Database").Value)
                };
                MySqlCommand insertLogQuery = new MySqlCommand(string.Format("INSERT INTO `logs`(datetime, tips, warnings, errors) VALUES(CURRENT_TIMESTAMP, {0}, {1}, {2})",
                    MySqlHelper.EscapeString(result.ChecksResult.Where(g => g.ItemType == CheckType.TIP).Count().ToString()),
                    MySqlHelper.EscapeString(result.ChecksResult.Where(g => g.ItemType == CheckType.WARNING).Count().ToString()),
                    MySqlHelper.EscapeString(result.ChecksResult.Where(g => g.ItemType == CheckType.ERROR).Count().ToString())), connection);
                await connection.OpenAsync();

                await insertLogQuery.ExecuteNonQueryAsync();

                if (connection != null)
                    connection.Close();
                connection.Dispose();
        }
            catch
            {
                Debug.WriteLine(string.Format("Logging result for {0}.", result.AddonName));
            }
}

        [HttpPost]
        [Route("checkaddon")]
        public async Task<IActionResult> CheckAddon(IFormFile file)
        {
            if (file == null)
                return View("Index");

            try
            {
                List<CheckResult> checksResult = new List<CheckResult>();
                int checksNumber = 0;
                int filesNumber = 0;
                if (file?.Length > 0)
                {
                    using (MemoryStream stream = new MemoryStream())
                    {
                        await file.CopyToAsync(stream, CancellationToken.None);
                        using (ZipArchive zip = new ZipArchive(stream))
                        {
                            foreach (var entry in zip.Entries)
                            {
                                if (!string.IsNullOrEmpty(entry.Name))
                                    filesNumber++;
                            }

                            foreach (Type typeCheck in Assembly.GetExecutingAssembly().GetTypes().Where(mytype => mytype.GetInterfaces().Contains(typeof(ICheck))))
                            {
                                checksNumber++;

                                ICheck check = (ICheck)Activator.CreateInstance(typeCheck);
                                foreach (var entry in zip.Entries)
                                {
                                    if (string.IsNullOrEmpty(entry.Name))
                                        continue;

                                    if (check.FileExtensions.Contains(Path.GetExtension(entry.Name)))
                                    {
                                        using (MemoryStream decompressedStream = new MemoryStream())
                                        {
                                            using (Stream compressStream = entry.Open())
                                            {
                                                await compressStream.CopyToAsync(decompressedStream);
                                            }

                                            using (StreamReader reader = new StreamReader(decompressedStream))
                                            {
                                                reader.BaseStream.Position = 0;
                                                reader.DiscardBufferedData();
                                                check.CheckFile(entry.FullName, reader, ref checksResult);
                                            }
                                        }

                                    }
                                }
                            }
                        }
                    }

                    CheckResultViewModel result = new CheckResultViewModel
                    {
                        AddonName = Path.GetFileNameWithoutExtension(file.FileName),
                        ChecksNumber = checksNumber,
                        FilesNumber = filesNumber,
                        ChecksResult = checksResult.OrderByDescending(x => (int)(x.ItemType)).ToList()
                    };

                    LogResult(result);

                    return View(result);
                }
            }
            catch
            {
                return View(new CheckResultViewModel
                {
                    AddonName = Path.GetFileNameWithoutExtension(file.FileName),
                    ChecksNumber = 0,
                    FilesNumber = 0,
                    ChecksResult = new List<CheckResult> { new CheckResult { ItemType = CheckType.ERROR, Message = "Error in processing your addon" } }
                });
            }
            return View("Index");
        }

        public IActionResult Index()
        {
            return View();
        }

        [Route("privacy")]
        public IActionResult Privacy()
        {
            return View();
        }

        [Route("about")]
        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AddonChecker/Views/Base/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h1>@ViewData["Title"]</h1>

<p>AddonChecker is World of Warcraft addon static analyzer for <b>7.x+</b> version of addon API.</p>
<p>Checks are based on common recommendations, best practices and API limitations of World of Warcraft.</p>
<p>
    There are three types of check results:
    <ul>
        <li><span class="badge badge-info">Tip</span> A tip to imrove the code.</li> 
        <li><span class="badge badge-warning">Warning</span> A warning which may lead to problems and unstable behaviour when using addon.</li> 
        <li><span class="badge badge-danger">Error</span> An error which may make your addon unusable at all.</li> 
    </ul>
</p>

AddonChecker/Views/Base/CheckAddon.cshtml
@model CheckResultViewModel
@{
    ViewData["Title"] = "Check results";
}
<h1>@Model.AddonName</h1>

<div class="alert alert-light" role="alert">
    <h4 class="alert-heading">@ViewData["Title"]</h4>
    <p>Procceed @Model.ChecksNumber check(s) on @Model.FilesNumber file(s).</p>

        <span class="badge badge-light">@Model.ChecksResult.Where(g => g.ItemType == AddonChecker.Checks.CheckType.TIP).Count()</span> <span class="badge badge-info">Tip(s)</span><br />
        <span class="badge badge-light">@Model.ChecksResult.Where(g => g.ItemType == AddonChecker.Checks.CheckType.WARNING).Count()</span> <span class="badge badge-warning">Warning(s)</span><br />
        <span class="badge badge-light">@Model.ChecksResult.Where(g => g.ItemType == AddonChecker.Checks.CheckType.ERROR).Count()</span> <span class="badge badge-danger">Error(s)</span>

    <hr>
    <p class="mb-0">@DateTime.Now.ToString()</p>
</div>

@foreach (var check in Model.ChecksResult)
{
<div class="alert alert-secondary" role="alert">
    <span class="badge badge-light">@Model.ChecksResult.IndexOf(check)</span>
    @if (check.ItemType == AddonChecker.Checks.CheckType.TIP)
    {
        <span class="badge badge-info">Tip</span>
    }
    @if (check.ItemType == AddonChecker.Checks.CheckType.WARNING)
    {
        <span class="badge badge-warning">Warning</span>
    }
    @if (check.ItemType == AddonChecker.Checks.CheckType.ERROR)
    {
        <span class="badge badge-danger">Error</span>
    }
    <span style="white-space: pre-line">@check.Message</span>
</div>
}

AddonChecker/Views/Base/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">World of Warcraft</h1>
    <h1 class="display-4">addon static analyzer</h1>

    <form method="post" enctype="multipart/form-data" asp-controller="Base" asp-action="checkaddon">
        <div class="form-group">
            <p>Upload your World of Warcraft addon</p>
            <span class="btn btn-success fileinput-button">
                <span>Select zip file with addon</span>
                <input type="file" name="file" accept="application/zip">
            </span>
        </div>
        <div class="form-group">
            <input type="submit" value="Upload" class="btn btn-info">
            <p>(10 MB zip file)</p>
        </div>
    </form>
</div>

AddonChecker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AddonChecker: @ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Base" asp-action="Index">AddonChecker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Base" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Base" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_PrivacyConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - AddonChecker by Yan Hrachou - <a asp-area="" asp-controller="Base" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

AddonChecker/Views/Shared/_PrivacyConsentPartial.cshtml
@using Microsoft.AspNetCore.Http.Features

@{
    var consentFeature = Context.Features.Get<ITrackingConsentFeature>();
    var showBanner = !consentFeature?.CanTrack ?? false;
    var cookieString = consentFeature?.CreateConsentCookie();
}

@if (showBanner)
{
<div id="privacyConsent" class="alert alert-info alert-dismissible fade show" role="alert">
    Checking of addons is being done in RAM and no addons data is being saved on the drives. <a asp-area="" asp-controller="Base" asp-action="Privacy">Learn More</a>.
    <button type="button" class="accept-policy close" data-dismiss="alert" aria-label="Close" data-cookie-string="@cookieString">
        <span aria-hidden="true">Accept</span>
    </button>
</div>
    <script>
        (function () {
            var button = document.querySelector("#privacyConsent button[data-cookie-string]");
            button.addEventListener("click", function (event) {
                document.cookie = button.dataset.cookieString;
            }, false);
        })();
    </script>
}